### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by adadouche**
*Issue #, if available:*

*Description of changes:*
 - updated packages version
 - disabled bucket versioning (since files are never overwritten anyway), enabled auto delete
 - adjusted PipelineNetwork stack constructor to add an id to name the stack

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by thomas-roos — DISMISSED** [review]
Looks good to me, Thank you for your contribution!

**Comment by thomas-roos** [comment]
Could may resolve the conflicts?

**Comment by adadouche** [comment]
conflict resolved

**Comment by thomas-roos** [comment]
Thank you, can you look in fixing the check failures?

**Comment by adadouche** [comment]
need to revisit my changes as discovered tests ere not successful

**Comment by thomas-roos** [comment]
Ok, did just briefly look over the tests and it seemed that the NAG needs an update.

**Pull request closed without merging**
