### PR TITLE
updated packages version & reverting versioned bucket and test cases

### PR DESCRIPTION
**Pull request by adadouche**
*Issue #, if available:*

*Description of changes:*
- updated packages version
- reverting versioned bucket and test cases

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by thomas-roos** [comment]
Hi, why reverting?

**Comment by adadouche** [comment]
I found a glitch after redeploying the pipelines, pipelines absolutely require versioning on the source buckets.
I initially disabled only tests and only activated the versioning where needed but felt it was a little dirty
I couldn't find a way to update the test to check for a specific property on a specific resource types (VersionConfiguration : Enabled for S3::Bucket resource type) so decided to revert the previous changes to avoid deployment problems

**Review by thomas-roos — DISMISSED** [review]
Thank you!

**Comment by thomas-roos** [comment]
Can you have a look into the failing tests?

**Comment by thomas-roos** [comment]
thank you!

**Pull request merged**
